//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasmaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public string nom_user { get; set; }
        public string motdepass { get; set; }
    }
}
